name: vietmap_flutter_gl
description: A Flutter map plugin for integrating Vietmap sdk inside a Flutter application, support for show a vector and raster map in Flutter. Supported on Android, iOS platforms .
version: 3.1.1
homepage: https://maps.vietmap.vn
repository: https://github.com/vietmap-company/vietmap_flutter_gl
issue_tracker: https://github.com/vietmap-company/vietmap_flutter_gl/issues

dependencies:
  flutter:
    sdk: flutter
  supercluster: ^3.1.0
  turf: ^0.0.10
  vietmap_gl_platform_interface: ^0.2.0
  maplibre_gl_web:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      path: maplibre_gl_web
      ref: release-0.16.0



flutter:
  plugin:
    platforms:
      android:
        package: vn.vietmap.vietmapgl
        pluginClass: VietmapGLPlugin 
      ios:
        pluginClass: VietmapPlugins
      web:
        default_package: mapbox_gl_web
  assets:
    - assets/center_pulse.png
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.0.0"


topics:
  - vietmap
  - map
  - flutter-map
  - map-api


assets:
  - assets/center_pulse.png